set(CPACK_GENERATOR
  TGZ
  ZIP
  )

set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 0)
set(CPACK_INSTALL_CMAKE_PROJECTS
  "${CMAKE_BINARY_DIR}"
  "${PROJECT_NAME}"
  ALL
  .
  )

set(CPACK_PROJECT_URL "https://github.com/luxater/cppmath")
set(CPACK_PACKAGE_VENDOR "Arden Rasmussen")
set(CPACK_PACKAGE_CONTACT "Arden Rasmussen <ardenrasmussen@lclark.edu>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Simplistic C++ Mathematics Library")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
if (PROJECT_VERSION_TWEAK)
  set(CPACK_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION}.${PROJECT_VERSION_TWEAK})
endif ()
set(CPACK_PACKAGE_RELOCATABLE ON)

set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "System Environment/Libraries")
set(CPACK_RPM_PACKAGE_URL ${CPACK_PROJECT_URL})
set(CPACK_RPM_PACKAGE_DESCRIPTION "Simplistic C++ Mathematics Library")

include(CPack)
